[package]
name = "czt"
version = "0.1.4"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/czt"
homepage = "https://github.com/stainless-steel/czt"
documentation = "https://stainless-steel.github.io/czt"
description = """
The package provides an algorithm to compute the chirp Z-transform."""

[dependencies]
complex = "0.7"
dft = "0.2"

[dev-dependencies]
assert = "0.6"
